// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: gogoxel/automation/v1/automation.proto

package automationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AutomationReadService_Health_FullMethodName     = "/gogoxel.automation.v1.AutomationReadService/Health"
	AutomationReadService_GetCamera_FullMethodName  = "/gogoxel.automation.v1.AutomationReadService/GetCamera"
	AutomationReadService_GetMetrics_FullMethodName = "/gogoxel.automation.v1.AutomationReadService/GetMetrics"
)

// AutomationReadServiceClient is the client API for AutomationReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutomationReadServiceClient interface {
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	GetCamera(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCameraResponse, error)
	GetMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMetricsResponse, error)
}

type automationReadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutomationReadServiceClient(cc grpc.ClientConnInterface) AutomationReadServiceClient {
	return &automationReadServiceClient{cc}
}

func (c *automationReadServiceClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AutomationReadService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationReadServiceClient) GetCamera(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCameraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCameraResponse)
	err := c.cc.Invoke(ctx, AutomationReadService_GetCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationReadServiceClient) GetMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, AutomationReadService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutomationReadServiceServer is the server API for AutomationReadService service.
// All implementations must embed UnimplementedAutomationReadServiceServer
// for forward compatibility.
type AutomationReadServiceServer interface {
	Health(context.Context, *Empty) (*HealthResponse, error)
	GetCamera(context.Context, *Empty) (*GetCameraResponse, error)
	GetMetrics(context.Context, *Empty) (*GetMetricsResponse, error)
	mustEmbedUnimplementedAutomationReadServiceServer()
}

// UnimplementedAutomationReadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutomationReadServiceServer struct{}

func (UnimplementedAutomationReadServiceServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAutomationReadServiceServer) GetCamera(context.Context, *Empty) (*GetCameraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCamera not implemented")
}
func (UnimplementedAutomationReadServiceServer) GetMetrics(context.Context, *Empty) (*GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedAutomationReadServiceServer) mustEmbedUnimplementedAutomationReadServiceServer() {}
func (UnimplementedAutomationReadServiceServer) testEmbeddedByValue()                               {}

// UnsafeAutomationReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutomationReadServiceServer will
// result in compilation errors.
type UnsafeAutomationReadServiceServer interface {
	mustEmbedUnimplementedAutomationReadServiceServer()
}

func RegisterAutomationReadServiceServer(s grpc.ServiceRegistrar, srv AutomationReadServiceServer) {
	// If the following call pancis, it indicates UnimplementedAutomationReadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutomationReadService_ServiceDesc, srv)
}

func _AutomationReadService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationReadServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationReadService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationReadServiceServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationReadService_GetCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationReadServiceServer).GetCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationReadService_GetCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationReadServiceServer).GetCamera(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationReadService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationReadServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationReadService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationReadServiceServer).GetMetrics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AutomationReadService_ServiceDesc is the grpc.ServiceDesc for AutomationReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutomationReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gogoxel.automation.v1.AutomationReadService",
	HandlerType: (*AutomationReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AutomationReadService_Health_Handler,
		},
		{
			MethodName: "GetCamera",
			Handler:    _AutomationReadService_GetCamera_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _AutomationReadService_GetMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gogoxel/automation/v1/automation.proto",
}

const (
	AutomationControlService_ResetEngine_FullMethodName           = "/gogoxel.automation.v1.AutomationControlService/ResetEngine"
	AutomationControlService_LoadGenerator_FullMethodName         = "/gogoxel.automation.v1.AutomationControlService/LoadGenerator"
	AutomationControlService_SetCamera_FullMethodName             = "/gogoxel.automation.v1.AutomationControlService/SetCamera"
	AutomationControlService_SetSimulationTickRate_FullMethodName = "/gogoxel.automation.v1.AutomationControlService/SetSimulationTickRate"
	AutomationControlService_InjectAction_FullMethodName          = "/gogoxel.automation.v1.AutomationControlService/InjectAction"
	AutomationControlService_ClickUiElement_FullMethodName        = "/gogoxel.automation.v1.AutomationControlService/ClickUiElement"
	AutomationControlService_StepTicks_FullMethodName             = "/gogoxel.automation.v1.AutomationControlService/StepTicks"
	AutomationControlService_StepFrames_FullMethodName            = "/gogoxel.automation.v1.AutomationControlService/StepFrames"
	AutomationControlService_WaitUntilReady_FullMethodName        = "/gogoxel.automation.v1.AutomationControlService/WaitUntilReady"
	AutomationControlService_ResetMetricsWindow_FullMethodName    = "/gogoxel.automation.v1.AutomationControlService/ResetMetricsWindow"
	AutomationControlService_Stop_FullMethodName                  = "/gogoxel.automation.v1.AutomationControlService/Stop"
)

// AutomationControlServiceClient is the client API for AutomationControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutomationControlServiceClient interface {
	ResetEngine(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResetEngineResponse, error)
	LoadGenerator(ctx context.Context, in *LoadGeneratorRequest, opts ...grpc.CallOption) (*LoadGeneratorResponse, error)
	SetCamera(ctx context.Context, in *SetCameraRequest, opts ...grpc.CallOption) (*SetCameraResponse, error)
	SetSimulationTickRate(ctx context.Context, in *SetSimulationTickRateRequest, opts ...grpc.CallOption) (*SetSimulationTickRateResponse, error)
	InjectAction(ctx context.Context, in *InjectActionRequest, opts ...grpc.CallOption) (*InjectActionResponse, error)
	ClickUiElement(ctx context.Context, in *ClickUiElementRequest, opts ...grpc.CallOption) (*ClickUiElementResponse, error)
	StepTicks(ctx context.Context, in *StepTicksRequest, opts ...grpc.CallOption) (*StepTicksResponse, error)
	StepFrames(ctx context.Context, in *StepFramesRequest, opts ...grpc.CallOption) (*StepFramesResponse, error)
	WaitUntilReady(ctx context.Context, in *WaitUntilReadyRequest, opts ...grpc.CallOption) (*WaitUntilReadyResponse, error)
	ResetMetricsWindow(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResetMetricsWindowResponse, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StopResponse, error)
}

type automationControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutomationControlServiceClient(cc grpc.ClientConnInterface) AutomationControlServiceClient {
	return &automationControlServiceClient{cc}
}

func (c *automationControlServiceClient) ResetEngine(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResetEngineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetEngineResponse)
	err := c.cc.Invoke(ctx, AutomationControlService_ResetEngine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlServiceClient) LoadGenerator(ctx context.Context, in *LoadGeneratorRequest, opts ...grpc.CallOption) (*LoadGeneratorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadGeneratorResponse)
	err := c.cc.Invoke(ctx, AutomationControlService_LoadGenerator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlServiceClient) SetCamera(ctx context.Context, in *SetCameraRequest, opts ...grpc.CallOption) (*SetCameraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCameraResponse)
	err := c.cc.Invoke(ctx, AutomationControlService_SetCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlServiceClient) SetSimulationTickRate(ctx context.Context, in *SetSimulationTickRateRequest, opts ...grpc.CallOption) (*SetSimulationTickRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSimulationTickRateResponse)
	err := c.cc.Invoke(ctx, AutomationControlService_SetSimulationTickRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlServiceClient) InjectAction(ctx context.Context, in *InjectActionRequest, opts ...grpc.CallOption) (*InjectActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectActionResponse)
	err := c.cc.Invoke(ctx, AutomationControlService_InjectAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlServiceClient) ClickUiElement(ctx context.Context, in *ClickUiElementRequest, opts ...grpc.CallOption) (*ClickUiElementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClickUiElementResponse)
	err := c.cc.Invoke(ctx, AutomationControlService_ClickUiElement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlServiceClient) StepTicks(ctx context.Context, in *StepTicksRequest, opts ...grpc.CallOption) (*StepTicksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepTicksResponse)
	err := c.cc.Invoke(ctx, AutomationControlService_StepTicks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlServiceClient) StepFrames(ctx context.Context, in *StepFramesRequest, opts ...grpc.CallOption) (*StepFramesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepFramesResponse)
	err := c.cc.Invoke(ctx, AutomationControlService_StepFrames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlServiceClient) WaitUntilReady(ctx context.Context, in *WaitUntilReadyRequest, opts ...grpc.CallOption) (*WaitUntilReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitUntilReadyResponse)
	err := c.cc.Invoke(ctx, AutomationControlService_WaitUntilReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlServiceClient) ResetMetricsWindow(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResetMetricsWindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetMetricsWindowResponse)
	err := c.cc.Invoke(ctx, AutomationControlService_ResetMetricsWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlServiceClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, AutomationControlService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutomationControlServiceServer is the server API for AutomationControlService service.
// All implementations must embed UnimplementedAutomationControlServiceServer
// for forward compatibility.
type AutomationControlServiceServer interface {
	ResetEngine(context.Context, *Empty) (*ResetEngineResponse, error)
	LoadGenerator(context.Context, *LoadGeneratorRequest) (*LoadGeneratorResponse, error)
	SetCamera(context.Context, *SetCameraRequest) (*SetCameraResponse, error)
	SetSimulationTickRate(context.Context, *SetSimulationTickRateRequest) (*SetSimulationTickRateResponse, error)
	InjectAction(context.Context, *InjectActionRequest) (*InjectActionResponse, error)
	ClickUiElement(context.Context, *ClickUiElementRequest) (*ClickUiElementResponse, error)
	StepTicks(context.Context, *StepTicksRequest) (*StepTicksResponse, error)
	StepFrames(context.Context, *StepFramesRequest) (*StepFramesResponse, error)
	WaitUntilReady(context.Context, *WaitUntilReadyRequest) (*WaitUntilReadyResponse, error)
	ResetMetricsWindow(context.Context, *Empty) (*ResetMetricsWindowResponse, error)
	Stop(context.Context, *Empty) (*StopResponse, error)
	mustEmbedUnimplementedAutomationControlServiceServer()
}

// UnimplementedAutomationControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutomationControlServiceServer struct{}

func (UnimplementedAutomationControlServiceServer) ResetEngine(context.Context, *Empty) (*ResetEngineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetEngine not implemented")
}
func (UnimplementedAutomationControlServiceServer) LoadGenerator(context.Context, *LoadGeneratorRequest) (*LoadGeneratorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadGenerator not implemented")
}
func (UnimplementedAutomationControlServiceServer) SetCamera(context.Context, *SetCameraRequest) (*SetCameraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCamera not implemented")
}
func (UnimplementedAutomationControlServiceServer) SetSimulationTickRate(context.Context, *SetSimulationTickRateRequest) (*SetSimulationTickRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSimulationTickRate not implemented")
}
func (UnimplementedAutomationControlServiceServer) InjectAction(context.Context, *InjectActionRequest) (*InjectActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectAction not implemented")
}
func (UnimplementedAutomationControlServiceServer) ClickUiElement(context.Context, *ClickUiElementRequest) (*ClickUiElementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClickUiElement not implemented")
}
func (UnimplementedAutomationControlServiceServer) StepTicks(context.Context, *StepTicksRequest) (*StepTicksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StepTicks not implemented")
}
func (UnimplementedAutomationControlServiceServer) StepFrames(context.Context, *StepFramesRequest) (*StepFramesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StepFrames not implemented")
}
func (UnimplementedAutomationControlServiceServer) WaitUntilReady(context.Context, *WaitUntilReadyRequest) (*WaitUntilReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitUntilReady not implemented")
}
func (UnimplementedAutomationControlServiceServer) ResetMetricsWindow(context.Context, *Empty) (*ResetMetricsWindowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetMetricsWindow not implemented")
}
func (UnimplementedAutomationControlServiceServer) Stop(context.Context, *Empty) (*StopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedAutomationControlServiceServer) mustEmbedUnimplementedAutomationControlServiceServer() {
}
func (UnimplementedAutomationControlServiceServer) testEmbeddedByValue() {}

// UnsafeAutomationControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutomationControlServiceServer will
// result in compilation errors.
type UnsafeAutomationControlServiceServer interface {
	mustEmbedUnimplementedAutomationControlServiceServer()
}

func RegisterAutomationControlServiceServer(s grpc.ServiceRegistrar, srv AutomationControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedAutomationControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutomationControlService_ServiceDesc, srv)
}

func _AutomationControlService_ResetEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServiceServer).ResetEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControlService_ResetEngine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServiceServer).ResetEngine(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControlService_LoadGenerator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadGeneratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServiceServer).LoadGenerator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControlService_LoadGenerator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServiceServer).LoadGenerator(ctx, req.(*LoadGeneratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControlService_SetCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCameraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServiceServer).SetCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControlService_SetCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServiceServer).SetCamera(ctx, req.(*SetCameraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControlService_SetSimulationTickRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSimulationTickRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServiceServer).SetSimulationTickRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControlService_SetSimulationTickRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServiceServer).SetSimulationTickRate(ctx, req.(*SetSimulationTickRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControlService_InjectAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServiceServer).InjectAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControlService_InjectAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServiceServer).InjectAction(ctx, req.(*InjectActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControlService_ClickUiElement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickUiElementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServiceServer).ClickUiElement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControlService_ClickUiElement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServiceServer).ClickUiElement(ctx, req.(*ClickUiElementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControlService_StepTicks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepTicksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServiceServer).StepTicks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControlService_StepTicks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServiceServer).StepTicks(ctx, req.(*StepTicksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControlService_StepFrames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepFramesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServiceServer).StepFrames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControlService_StepFrames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServiceServer).StepFrames(ctx, req.(*StepFramesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControlService_WaitUntilReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitUntilReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServiceServer).WaitUntilReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControlService_WaitUntilReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServiceServer).WaitUntilReady(ctx, req.(*WaitUntilReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControlService_ResetMetricsWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServiceServer).ResetMetricsWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControlService_ResetMetricsWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServiceServer).ResetMetricsWindow(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControlService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControlService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServiceServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AutomationControlService_ServiceDesc is the grpc.ServiceDesc for AutomationControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutomationControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gogoxel.automation.v1.AutomationControlService",
	HandlerType: (*AutomationControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResetEngine",
			Handler:    _AutomationControlService_ResetEngine_Handler,
		},
		{
			MethodName: "LoadGenerator",
			Handler:    _AutomationControlService_LoadGenerator_Handler,
		},
		{
			MethodName: "SetCamera",
			Handler:    _AutomationControlService_SetCamera_Handler,
		},
		{
			MethodName: "SetSimulationTickRate",
			Handler:    _AutomationControlService_SetSimulationTickRate_Handler,
		},
		{
			MethodName: "InjectAction",
			Handler:    _AutomationControlService_InjectAction_Handler,
		},
		{
			MethodName: "ClickUiElement",
			Handler:    _AutomationControlService_ClickUiElement_Handler,
		},
		{
			MethodName: "StepTicks",
			Handler:    _AutomationControlService_StepTicks_Handler,
		},
		{
			MethodName: "StepFrames",
			Handler:    _AutomationControlService_StepFrames_Handler,
		},
		{
			MethodName: "WaitUntilReady",
			Handler:    _AutomationControlService_WaitUntilReady_Handler,
		},
		{
			MethodName: "ResetMetricsWindow",
			Handler:    _AutomationControlService_ResetMetricsWindow_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _AutomationControlService_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gogoxel/automation/v1/automation.proto",
}

const (
	AutomationArtifactService_CaptureScreenshot_FullMethodName = "/gogoxel.automation.v1.AutomationArtifactService/CaptureScreenshot"
	AutomationArtifactService_ExportTrace_FullMethodName       = "/gogoxel.automation.v1.AutomationArtifactService/ExportTrace"
)

// AutomationArtifactServiceClient is the client API for AutomationArtifactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutomationArtifactServiceClient interface {
	CaptureScreenshot(ctx context.Context, in *CaptureScreenshotRequest, opts ...grpc.CallOption) (*CaptureScreenshotResponse, error)
	ExportTrace(ctx context.Context, in *ExportTraceRequest, opts ...grpc.CallOption) (*ExportTraceResponse, error)
}

type automationArtifactServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutomationArtifactServiceClient(cc grpc.ClientConnInterface) AutomationArtifactServiceClient {
	return &automationArtifactServiceClient{cc}
}

func (c *automationArtifactServiceClient) CaptureScreenshot(ctx context.Context, in *CaptureScreenshotRequest, opts ...grpc.CallOption) (*CaptureScreenshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureScreenshotResponse)
	err := c.cc.Invoke(ctx, AutomationArtifactService_CaptureScreenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationArtifactServiceClient) ExportTrace(ctx context.Context, in *ExportTraceRequest, opts ...grpc.CallOption) (*ExportTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportTraceResponse)
	err := c.cc.Invoke(ctx, AutomationArtifactService_ExportTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutomationArtifactServiceServer is the server API for AutomationArtifactService service.
// All implementations must embed UnimplementedAutomationArtifactServiceServer
// for forward compatibility.
type AutomationArtifactServiceServer interface {
	CaptureScreenshot(context.Context, *CaptureScreenshotRequest) (*CaptureScreenshotResponse, error)
	ExportTrace(context.Context, *ExportTraceRequest) (*ExportTraceResponse, error)
	mustEmbedUnimplementedAutomationArtifactServiceServer()
}

// UnimplementedAutomationArtifactServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutomationArtifactServiceServer struct{}

func (UnimplementedAutomationArtifactServiceServer) CaptureScreenshot(context.Context, *CaptureScreenshotRequest) (*CaptureScreenshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaptureScreenshot not implemented")
}
func (UnimplementedAutomationArtifactServiceServer) ExportTrace(context.Context, *ExportTraceRequest) (*ExportTraceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportTrace not implemented")
}
func (UnimplementedAutomationArtifactServiceServer) mustEmbedUnimplementedAutomationArtifactServiceServer() {
}
func (UnimplementedAutomationArtifactServiceServer) testEmbeddedByValue() {}

// UnsafeAutomationArtifactServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutomationArtifactServiceServer will
// result in compilation errors.
type UnsafeAutomationArtifactServiceServer interface {
	mustEmbedUnimplementedAutomationArtifactServiceServer()
}

func RegisterAutomationArtifactServiceServer(s grpc.ServiceRegistrar, srv AutomationArtifactServiceServer) {
	// If the following call pancis, it indicates UnimplementedAutomationArtifactServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutomationArtifactService_ServiceDesc, srv)
}

func _AutomationArtifactService_CaptureScreenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationArtifactServiceServer).CaptureScreenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationArtifactService_CaptureScreenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationArtifactServiceServer).CaptureScreenshot(ctx, req.(*CaptureScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationArtifactService_ExportTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationArtifactServiceServer).ExportTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationArtifactService_ExportTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationArtifactServiceServer).ExportTrace(ctx, req.(*ExportTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutomationArtifactService_ServiceDesc is the grpc.ServiceDesc for AutomationArtifactService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutomationArtifactService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gogoxel.automation.v1.AutomationArtifactService",
	HandlerType: (*AutomationArtifactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CaptureScreenshot",
			Handler:    _AutomationArtifactService_CaptureScreenshot_Handler,
		},
		{
			MethodName: "ExportTrace",
			Handler:    _AutomationArtifactService_ExportTrace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gogoxel/automation/v1/automation.proto",
}
