// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: gogoxel/automation/v1/automation.proto

package automationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionState int32

const (
	ActionState_ACTION_STATE_UNSPECIFIED ActionState = 0
	ActionState_ACTION_STATE_PRESS       ActionState = 1
	ActionState_ACTION_STATE_RELEASE     ActionState = 2
)

// Enum value maps for ActionState.
var (
	ActionState_name = map[int32]string{
		0: "ACTION_STATE_UNSPECIFIED",
		1: "ACTION_STATE_PRESS",
		2: "ACTION_STATE_RELEASE",
	}
	ActionState_value = map[string]int32{
		"ACTION_STATE_UNSPECIFIED": 0,
		"ACTION_STATE_PRESS":       1,
		"ACTION_STATE_RELEASE":     2,
	}
)

func (x ActionState) Enum() *ActionState {
	p := new(ActionState)
	*p = x
	return p
}

func (x ActionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionState) Descriptor() protoreflect.EnumDescriptor {
	return file_gogoxel_automation_v1_automation_proto_enumTypes[0].Descriptor()
}

func (ActionState) Type() protoreflect.EnumType {
	return &file_gogoxel_automation_v1_automation_proto_enumTypes[0]
}

func (x ActionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionState.Descriptor instead.
func (ActionState) EnumDescriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{0}
}

type EditMode int32

const (
	EditMode_EDIT_MODE_UNSPECIFIED EditMode = 0
	EditMode_EDIT_MODE_PLACE       EditMode = 1
	EditMode_EDIT_MODE_REMOVE      EditMode = 2
)

// Enum value maps for EditMode.
var (
	EditMode_name = map[int32]string{
		0: "EDIT_MODE_UNSPECIFIED",
		1: "EDIT_MODE_PLACE",
		2: "EDIT_MODE_REMOVE",
	}
	EditMode_value = map[string]int32{
		"EDIT_MODE_UNSPECIFIED": 0,
		"EDIT_MODE_PLACE":       1,
		"EDIT_MODE_REMOVE":      2,
	}
)

func (x EditMode) Enum() *EditMode {
	p := new(EditMode)
	*p = x
	return p
}

func (x EditMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EditMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gogoxel_automation_v1_automation_proto_enumTypes[1].Descriptor()
}

func (EditMode) Type() protoreflect.EnumType {
	return &file_gogoxel_automation_v1_automation_proto_enumTypes[1]
}

func (x EditMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EditMode.Descriptor instead.
func (EditMode) EnumDescriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{0}
}

type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{1}
}

func (x *Vector3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Camera struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Vector3               `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	YawDeg        float32                `protobuf:"fixed32,2,opt,name=yaw_deg,json=yawDeg,proto3" json:"yaw_deg,omitempty"`
	PitchDeg      float32                `protobuf:"fixed32,3,opt,name=pitch_deg,json=pitchDeg,proto3" json:"pitch_deg,omitempty"`
	FovDeg        float32                `protobuf:"fixed32,4,opt,name=fov_deg,json=fovDeg,proto3" json:"fov_deg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Camera) Reset() {
	*x = Camera{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Camera) ProtoMessage() {}

func (x *Camera) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Camera.ProtoReflect.Descriptor instead.
func (*Camera) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{2}
}

func (x *Camera) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Camera) GetYawDeg() float32 {
	if x != nil {
		return x.YawDeg
	}
	return 0
}

func (x *Camera) GetPitchDeg() float32 {
	if x != nil {
		return x.PitchDeg
	}
	return 0
}

func (x *Camera) GetFovDeg() float32 {
	if x != nil {
		return x.FovDeg
	}
	return 0
}

type Readiness struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EngineInitialized   bool                   `protobuf:"varint,1,opt,name=engine_initialized,json=engineInitialized,proto3" json:"engine_initialized,omitempty"`
	RendererInitialized bool                   `protobuf:"varint,2,opt,name=renderer_initialized,json=rendererInitialized,proto3" json:"renderer_initialized,omitempty"`
	SceneLoaded         bool                   `protobuf:"varint,3,opt,name=scene_loaded,json=sceneLoaded,proto3" json:"scene_loaded,omitempty"`
	StreamingPlanned    bool                   `protobuf:"varint,4,opt,name=streaming_planned,json=streamingPlanned,proto3" json:"streaming_planned,omitempty"`
	StreamingSettled    bool                   `protobuf:"varint,5,opt,name=streaming_settled,json=streamingSettled,proto3" json:"streaming_settled,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Readiness) Reset() {
	*x = Readiness{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Readiness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Readiness) ProtoMessage() {}

func (x *Readiness) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Readiness.ProtoReflect.Descriptor instead.
func (*Readiness) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{3}
}

func (x *Readiness) GetEngineInitialized() bool {
	if x != nil {
		return x.EngineInitialized
	}
	return false
}

func (x *Readiness) GetRendererInitialized() bool {
	if x != nil {
		return x.RendererInitialized
	}
	return false
}

func (x *Readiness) GetSceneLoaded() bool {
	if x != nil {
		return x.SceneLoaded
	}
	return false
}

func (x *Readiness) GetStreamingPlanned() bool {
	if x != nil {
		return x.StreamingPlanned
	}
	return false
}

func (x *Readiness) GetStreamingSettled() bool {
	if x != nil {
		return x.StreamingSettled
	}
	return false
}

type WaitCriteria struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RequireRenderer         bool                   `protobuf:"varint,1,opt,name=require_renderer,json=requireRenderer,proto3" json:"require_renderer,omitempty"`
	RequireSceneLoaded      bool                   `protobuf:"varint,2,opt,name=require_scene_loaded,json=requireSceneLoaded,proto3" json:"require_scene_loaded,omitempty"`
	RequireStreamingSettled bool                   `protobuf:"varint,3,opt,name=require_streaming_settled,json=requireStreamingSettled,proto3" json:"require_streaming_settled,omitempty"`
	MaxTicks                uint32                 `protobuf:"varint,4,opt,name=max_ticks,json=maxTicks,proto3" json:"max_ticks,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *WaitCriteria) Reset() {
	*x = WaitCriteria{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitCriteria) ProtoMessage() {}

func (x *WaitCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitCriteria.ProtoReflect.Descriptor instead.
func (*WaitCriteria) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{4}
}

func (x *WaitCriteria) GetRequireRenderer() bool {
	if x != nil {
		return x.RequireRenderer
	}
	return false
}

func (x *WaitCriteria) GetRequireSceneLoaded() bool {
	if x != nil {
		return x.RequireSceneLoaded
	}
	return false
}

func (x *WaitCriteria) GetRequireStreamingSettled() bool {
	if x != nil {
		return x.RequireStreamingSettled
	}
	return false
}

func (x *WaitCriteria) GetMaxTicks() uint32 {
	if x != nil {
		return x.MaxTicks
	}
	return 0
}

type MetricsSnapshot struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Camera                       *Camera                `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
	CurrentGenerator             string                 `protobuf:"bytes,2,opt,name=current_generator,json=currentGenerator,proto3" json:"current_generator,omitempty"`
	RamBytes                     uint64                 `protobuf:"varint,3,opt,name=ram_bytes,json=ramBytes,proto3" json:"ram_bytes,omitempty"`
	SystemRamBytes               uint64                 `protobuf:"varint,4,opt,name=system_ram_bytes,json=systemRamBytes,proto3" json:"system_ram_bytes,omitempty"`
	VramBytes                    uint64                 `protobuf:"varint,5,opt,name=vram_bytes,json=vramBytes,proto3" json:"vram_bytes,omitempty"`
	ChunkRamBytes                uint64                 `protobuf:"varint,6,opt,name=chunk_ram_bytes,json=chunkRamBytes,proto3" json:"chunk_ram_bytes,omitempty"`
	NodeCount                    uint64                 `protobuf:"varint,7,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	BrickCount                   uint64                 `protobuf:"varint,8,opt,name=brick_count,json=brickCount,proto3" json:"brick_count,omitempty"`
	WorldSize                    uint64                 `protobuf:"varint,9,opt,name=world_size,json=worldSize,proto3" json:"world_size,omitempty"`
	ResidentBrickCount           uint64                 `protobuf:"varint,10,opt,name=resident_brick_count,json=residentBrickCount,proto3" json:"resident_brick_count,omitempty"`
	StreamingDesiredReady        bool                   `protobuf:"varint,11,opt,name=streaming_desired_ready,json=streamingDesiredReady,proto3" json:"streaming_desired_ready,omitempty"`
	StreamingPendingDesiredCount uint64                 `protobuf:"varint,12,opt,name=streaming_pending_desired_count,json=streamingPendingDesiredCount,proto3" json:"streaming_pending_desired_count,omitempty"`
	StreamingResidentLimit       uint64                 `protobuf:"varint,13,opt,name=streaming_resident_limit,json=streamingResidentLimit,proto3" json:"streaming_resident_limit,omitempty"`
	StreamingUploadBudget        uint64                 `protobuf:"varint,14,opt,name=streaming_upload_budget,json=streamingUploadBudget,proto3" json:"streaming_upload_budget,omitempty"`
	PresentMode                  string                 `protobuf:"bytes,15,opt,name=present_mode,json=presentMode,proto3" json:"present_mode,omitempty"`
	RendererDevice               string                 `protobuf:"bytes,16,opt,name=renderer_device,json=rendererDevice,proto3" json:"renderer_device,omitempty"`
	AverageFps                   float64                `protobuf:"fixed64,17,opt,name=average_fps,json=averageFps,proto3" json:"average_fps,omitempty"`
	AverageFrameTimeMs           float64                `protobuf:"fixed64,18,opt,name=average_frame_time_ms,json=averageFrameTimeMs,proto3" json:"average_frame_time_ms,omitempty"`
	P95FrameTimeMs               float64                `protobuf:"fixed64,19,opt,name=p95_frame_time_ms,json=p95FrameTimeMs,proto3" json:"p95_frame_time_ms,omitempty"`
	FrameSampleCount             uint64                 `protobuf:"varint,20,opt,name=frame_sample_count,json=frameSampleCount,proto3" json:"frame_sample_count,omitempty"`
	AverageGpuFrameTimeMs        float64                `protobuf:"fixed64,21,opt,name=average_gpu_frame_time_ms,json=averageGpuFrameTimeMs,proto3" json:"average_gpu_frame_time_ms,omitempty"`
	P95GpuFrameTimeMs            float64                `protobuf:"fixed64,22,opt,name=p95_gpu_frame_time_ms,json=p95GpuFrameTimeMs,proto3" json:"p95_gpu_frame_time_ms,omitempty"`
	GpuFrameSampleCount          uint64                 `protobuf:"varint,23,opt,name=gpu_frame_sample_count,json=gpuFrameSampleCount,proto3" json:"gpu_frame_sample_count,omitempty"`
	HeapAllocDeltaBytes          uint64                 `protobuf:"varint,24,opt,name=heap_alloc_delta_bytes,json=heapAllocDeltaBytes,proto3" json:"heap_alloc_delta_bytes,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *MetricsSnapshot) Reset() {
	*x = MetricsSnapshot{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSnapshot) ProtoMessage() {}

func (x *MetricsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSnapshot.ProtoReflect.Descriptor instead.
func (*MetricsSnapshot) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{5}
}

func (x *MetricsSnapshot) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

func (x *MetricsSnapshot) GetCurrentGenerator() string {
	if x != nil {
		return x.CurrentGenerator
	}
	return ""
}

func (x *MetricsSnapshot) GetRamBytes() uint64 {
	if x != nil {
		return x.RamBytes
	}
	return 0
}

func (x *MetricsSnapshot) GetSystemRamBytes() uint64 {
	if x != nil {
		return x.SystemRamBytes
	}
	return 0
}

func (x *MetricsSnapshot) GetVramBytes() uint64 {
	if x != nil {
		return x.VramBytes
	}
	return 0
}

func (x *MetricsSnapshot) GetChunkRamBytes() uint64 {
	if x != nil {
		return x.ChunkRamBytes
	}
	return 0
}

func (x *MetricsSnapshot) GetNodeCount() uint64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *MetricsSnapshot) GetBrickCount() uint64 {
	if x != nil {
		return x.BrickCount
	}
	return 0
}

func (x *MetricsSnapshot) GetWorldSize() uint64 {
	if x != nil {
		return x.WorldSize
	}
	return 0
}

func (x *MetricsSnapshot) GetResidentBrickCount() uint64 {
	if x != nil {
		return x.ResidentBrickCount
	}
	return 0
}

func (x *MetricsSnapshot) GetStreamingDesiredReady() bool {
	if x != nil {
		return x.StreamingDesiredReady
	}
	return false
}

func (x *MetricsSnapshot) GetStreamingPendingDesiredCount() uint64 {
	if x != nil {
		return x.StreamingPendingDesiredCount
	}
	return 0
}

func (x *MetricsSnapshot) GetStreamingResidentLimit() uint64 {
	if x != nil {
		return x.StreamingResidentLimit
	}
	return 0
}

func (x *MetricsSnapshot) GetStreamingUploadBudget() uint64 {
	if x != nil {
		return x.StreamingUploadBudget
	}
	return 0
}

func (x *MetricsSnapshot) GetPresentMode() string {
	if x != nil {
		return x.PresentMode
	}
	return ""
}

func (x *MetricsSnapshot) GetRendererDevice() string {
	if x != nil {
		return x.RendererDevice
	}
	return ""
}

func (x *MetricsSnapshot) GetAverageFps() float64 {
	if x != nil {
		return x.AverageFps
	}
	return 0
}

func (x *MetricsSnapshot) GetAverageFrameTimeMs() float64 {
	if x != nil {
		return x.AverageFrameTimeMs
	}
	return 0
}

func (x *MetricsSnapshot) GetP95FrameTimeMs() float64 {
	if x != nil {
		return x.P95FrameTimeMs
	}
	return 0
}

func (x *MetricsSnapshot) GetFrameSampleCount() uint64 {
	if x != nil {
		return x.FrameSampleCount
	}
	return 0
}

func (x *MetricsSnapshot) GetAverageGpuFrameTimeMs() float64 {
	if x != nil {
		return x.AverageGpuFrameTimeMs
	}
	return 0
}

func (x *MetricsSnapshot) GetP95GpuFrameTimeMs() float64 {
	if x != nil {
		return x.P95GpuFrameTimeMs
	}
	return 0
}

func (x *MetricsSnapshot) GetGpuFrameSampleCount() uint64 {
	if x != nil {
		return x.GpuFrameSampleCount
	}
	return 0
}

func (x *MetricsSnapshot) GetHeapAllocDeltaBytes() uint64 {
	if x != nil {
		return x.HeapAllocDeltaBytes
	}
	return 0
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	RequestedName string                 `protobuf:"bytes,2,opt,name=requested_name,json=requestedName,proto3" json:"requested_name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{6}
}

func (x *Artifact) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Artifact) GetRequestedName() string {
	if x != nil {
		return x.RequestedName
	}
	return ""
}

func (x *Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Artifact) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type NormalizedCursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NormalizedX   float32                `protobuf:"fixed32,1,opt,name=normalized_x,json=normalizedX,proto3" json:"normalized_x,omitempty"`
	NormalizedY   float32                `protobuf:"fixed32,2,opt,name=normalized_y,json=normalizedY,proto3" json:"normalized_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedCursor) Reset() {
	*x = NormalizedCursor{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedCursor) ProtoMessage() {}

func (x *NormalizedCursor) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedCursor.ProtoReflect.Descriptor instead.
func (*NormalizedCursor) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{7}
}

func (x *NormalizedCursor) GetNormalizedX() float32 {
	if x != nil {
		return x.NormalizedX
	}
	return 0
}

func (x *NormalizedCursor) GetNormalizedY() float32 {
	if x != nil {
		return x.NormalizedY
	}
	return 0
}

type VoxelCoordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             uint32                 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             uint32                 `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoxelCoordinates) Reset() {
	*x = VoxelCoordinates{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoxelCoordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoxelCoordinates) ProtoMessage() {}

func (x *VoxelCoordinates) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoxelCoordinates.ProtoReflect.Descriptor instead.
func (*VoxelCoordinates) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{8}
}

func (x *VoxelCoordinates) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *VoxelCoordinates) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *VoxelCoordinates) GetZ() uint32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readiness     *Readiness             `protobuf:"bytes,1,opt,name=readiness,proto3" json:"readiness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetReadiness() *Readiness {
	if x != nil {
		return x.Readiness
	}
	return nil
}

type GetCameraResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Camera        *Camera                `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCameraResponse) Reset() {
	*x = GetCameraResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCameraResponse) ProtoMessage() {}

func (x *GetCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCameraResponse.ProtoReflect.Descriptor instead.
func (*GetCameraResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{10}
}

func (x *GetCameraResponse) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *MetricsSnapshot       `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{11}
}

func (x *GetMetricsResponse) GetMetrics() *MetricsSnapshot {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ResetEngineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readiness     *Readiness             `protobuf:"bytes,1,opt,name=readiness,proto3" json:"readiness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetEngineResponse) Reset() {
	*x = ResetEngineResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetEngineResponse) ProtoMessage() {}

func (x *ResetEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetEngineResponse.ProtoReflect.Descriptor instead.
func (*ResetEngineResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{12}
}

func (x *ResetEngineResponse) GetReadiness() *Readiness {
	if x != nil {
		return x.Readiness
	}
	return nil
}

type LoadGeneratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ChunkX        int32                  `protobuf:"varint,2,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkY        int32                  `protobuf:"varint,3,opt,name=chunk_y,json=chunkY,proto3" json:"chunk_y,omitempty"`
	ChunkRange    uint32                 `protobuf:"varint,4,opt,name=chunk_range,json=chunkRange,proto3" json:"chunk_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadGeneratorRequest) Reset() {
	*x = LoadGeneratorRequest{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadGeneratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGeneratorRequest) ProtoMessage() {}

func (x *LoadGeneratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGeneratorRequest.ProtoReflect.Descriptor instead.
func (*LoadGeneratorRequest) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{13}
}

func (x *LoadGeneratorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadGeneratorRequest) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *LoadGeneratorRequest) GetChunkY() int32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

func (x *LoadGeneratorRequest) GetChunkRange() uint32 {
	if x != nil {
		return x.ChunkRange
	}
	return 0
}

type LoadGeneratorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readiness     *Readiness             `protobuf:"bytes,1,opt,name=readiness,proto3" json:"readiness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadGeneratorResponse) Reset() {
	*x = LoadGeneratorResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadGeneratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadGeneratorResponse) ProtoMessage() {}

func (x *LoadGeneratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadGeneratorResponse.ProtoReflect.Descriptor instead.
func (*LoadGeneratorResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{14}
}

func (x *LoadGeneratorResponse) GetReadiness() *Readiness {
	if x != nil {
		return x.Readiness
	}
	return nil
}

type SetCameraRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Camera        *Camera                `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCameraRequest) Reset() {
	*x = SetCameraRequest{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCameraRequest) ProtoMessage() {}

func (x *SetCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCameraRequest.ProtoReflect.Descriptor instead.
func (*SetCameraRequest) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{15}
}

func (x *SetCameraRequest) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type SetCameraResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Camera        *Camera                `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCameraResponse) Reset() {
	*x = SetCameraResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCameraResponse) ProtoMessage() {}

func (x *SetCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCameraResponse.ProtoReflect.Descriptor instead.
func (*SetCameraResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{16}
}

func (x *SetCameraResponse) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type SetSimulationTickRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TickRateHz    uint32                 `protobuf:"varint,1,opt,name=tick_rate_hz,json=tickRateHz,proto3" json:"tick_rate_hz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSimulationTickRateRequest) Reset() {
	*x = SetSimulationTickRateRequest{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSimulationTickRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSimulationTickRateRequest) ProtoMessage() {}

func (x *SetSimulationTickRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSimulationTickRateRequest.ProtoReflect.Descriptor instead.
func (*SetSimulationTickRateRequest) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{17}
}

func (x *SetSimulationTickRateRequest) GetTickRateHz() uint32 {
	if x != nil {
		return x.TickRateHz
	}
	return 0
}

type SetSimulationTickRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TickRateHz    uint32                 `protobuf:"varint,1,opt,name=tick_rate_hz,json=tickRateHz,proto3" json:"tick_rate_hz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSimulationTickRateResponse) Reset() {
	*x = SetSimulationTickRateResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSimulationTickRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSimulationTickRateResponse) ProtoMessage() {}

func (x *SetSimulationTickRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSimulationTickRateResponse.ProtoReflect.Descriptor instead.
func (*SetSimulationTickRateResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{18}
}

func (x *SetSimulationTickRateResponse) GetTickRateHz() uint32 {
	if x != nil {
		return x.TickRateHz
	}
	return 0
}

type InjectActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	State         ActionState            `protobuf:"varint,2,opt,name=state,proto3,enum=gogoxel.automation.v1.ActionState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectActionRequest) Reset() {
	*x = InjectActionRequest{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectActionRequest) ProtoMessage() {}

func (x *InjectActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectActionRequest.ProtoReflect.Descriptor instead.
func (*InjectActionRequest) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{19}
}

func (x *InjectActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *InjectActionRequest) GetState() ActionState {
	if x != nil {
		return x.State
	}
	return ActionState_ACTION_STATE_UNSPECIFIED
}

type InjectActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readiness     *Readiness             `protobuf:"bytes,1,opt,name=readiness,proto3" json:"readiness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectActionResponse) Reset() {
	*x = InjectActionResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectActionResponse) ProtoMessage() {}

func (x *InjectActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectActionResponse.ProtoReflect.Descriptor instead.
func (*InjectActionResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{20}
}

func (x *InjectActionResponse) GetReadiness() *Readiness {
	if x != nil {
		return x.Readiness
	}
	return nil
}

type SetSelectedMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialName  string                 `protobuf:"bytes,1,opt,name=material_name,json=materialName,proto3" json:"material_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSelectedMaterialRequest) Reset() {
	*x = SetSelectedMaterialRequest{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSelectedMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSelectedMaterialRequest) ProtoMessage() {}

func (x *SetSelectedMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSelectedMaterialRequest.ProtoReflect.Descriptor instead.
func (*SetSelectedMaterialRequest) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{21}
}

func (x *SetSelectedMaterialRequest) GetMaterialName() string {
	if x != nil {
		return x.MaterialName
	}
	return ""
}

type SetSelectedMaterialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialName  string                 `protobuf:"bytes,1,opt,name=material_name,json=materialName,proto3" json:"material_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSelectedMaterialResponse) Reset() {
	*x = SetSelectedMaterialResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSelectedMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSelectedMaterialResponse) ProtoMessage() {}

func (x *SetSelectedMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSelectedMaterialResponse.ProtoReflect.Descriptor instead.
func (*SetSelectedMaterialResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{22}
}

func (x *SetSelectedMaterialResponse) GetMaterialName() string {
	if x != nil {
		return x.MaterialName
	}
	return ""
}

type EditAtCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *NormalizedCursor      `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Mode          EditMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=gogoxel.automation.v1.EditMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditAtCursorRequest) Reset() {
	*x = EditAtCursorRequest{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditAtCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAtCursorRequest) ProtoMessage() {}

func (x *EditAtCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAtCursorRequest.ProtoReflect.Descriptor instead.
func (*EditAtCursorRequest) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{23}
}

func (x *EditAtCursorRequest) GetCursor() *NormalizedCursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *EditAtCursorRequest) GetMode() EditMode {
	if x != nil {
		return x.Mode
	}
	return EditMode_EDIT_MODE_UNSPECIFIED
}

type EditAtCursorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	HitVoxel      *VoxelCoordinates      `protobuf:"bytes,2,opt,name=hit_voxel,json=hitVoxel,proto3" json:"hit_voxel,omitempty"`
	TargetVoxel   *VoxelCoordinates      `protobuf:"bytes,3,opt,name=target_voxel,json=targetVoxel,proto3" json:"target_voxel,omitempty"`
	MaterialName  string                 `protobuf:"bytes,4,opt,name=material_name,json=materialName,proto3" json:"material_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditAtCursorResponse) Reset() {
	*x = EditAtCursorResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditAtCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAtCursorResponse) ProtoMessage() {}

func (x *EditAtCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAtCursorResponse.ProtoReflect.Descriptor instead.
func (*EditAtCursorResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{24}
}

func (x *EditAtCursorResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *EditAtCursorResponse) GetHitVoxel() *VoxelCoordinates {
	if x != nil {
		return x.HitVoxel
	}
	return nil
}

func (x *EditAtCursorResponse) GetTargetVoxel() *VoxelCoordinates {
	if x != nil {
		return x.TargetVoxel
	}
	return nil
}

func (x *EditAtCursorResponse) GetMaterialName() string {
	if x != nil {
		return x.MaterialName
	}
	return ""
}

type ClickUiElementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicalId     string                 `protobuf:"bytes,1,opt,name=logical_id,json=logicalId,proto3" json:"logical_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickUiElementRequest) Reset() {
	*x = ClickUiElementRequest{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickUiElementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickUiElementRequest) ProtoMessage() {}

func (x *ClickUiElementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickUiElementRequest.ProtoReflect.Descriptor instead.
func (*ClickUiElementRequest) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{25}
}

func (x *ClickUiElementRequest) GetLogicalId() string {
	if x != nil {
		return x.LogicalId
	}
	return ""
}

type ClickUiElementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readiness     *Readiness             `protobuf:"bytes,1,opt,name=readiness,proto3" json:"readiness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickUiElementResponse) Reset() {
	*x = ClickUiElementResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickUiElementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickUiElementResponse) ProtoMessage() {}

func (x *ClickUiElementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickUiElementResponse.ProtoReflect.Descriptor instead.
func (*ClickUiElementResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{26}
}

func (x *ClickUiElementResponse) GetReadiness() *Readiness {
	if x != nil {
		return x.Readiness
	}
	return nil
}

type StepTicksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticks         uint32                 `protobuf:"varint,1,opt,name=ticks,proto3" json:"ticks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepTicksRequest) Reset() {
	*x = StepTicksRequest{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepTicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepTicksRequest) ProtoMessage() {}

func (x *StepTicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepTicksRequest.ProtoReflect.Descriptor instead.
func (*StepTicksRequest) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{27}
}

func (x *StepTicksRequest) GetTicks() uint32 {
	if x != nil {
		return x.Ticks
	}
	return 0
}

type StepTicksResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TicksExecuted  uint32                 `protobuf:"varint,1,opt,name=ticks_executed,json=ticksExecuted,proto3" json:"ticks_executed,omitempty"`
	FramesExecuted uint32                 `protobuf:"varint,2,opt,name=frames_executed,json=framesExecuted,proto3" json:"frames_executed,omitempty"`
	Metrics        *MetricsSnapshot       `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StepTicksResponse) Reset() {
	*x = StepTicksResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepTicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepTicksResponse) ProtoMessage() {}

func (x *StepTicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepTicksResponse.ProtoReflect.Descriptor instead.
func (*StepTicksResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{28}
}

func (x *StepTicksResponse) GetTicksExecuted() uint32 {
	if x != nil {
		return x.TicksExecuted
	}
	return 0
}

func (x *StepTicksResponse) GetFramesExecuted() uint32 {
	if x != nil {
		return x.FramesExecuted
	}
	return 0
}

func (x *StepTicksResponse) GetMetrics() *MetricsSnapshot {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type StepFramesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        uint32                 `protobuf:"varint,1,opt,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepFramesRequest) Reset() {
	*x = StepFramesRequest{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepFramesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepFramesRequest) ProtoMessage() {}

func (x *StepFramesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepFramesRequest.ProtoReflect.Descriptor instead.
func (*StepFramesRequest) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{29}
}

func (x *StepFramesRequest) GetFrames() uint32 {
	if x != nil {
		return x.Frames
	}
	return 0
}

type StepFramesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TicksExecuted  uint32                 `protobuf:"varint,1,opt,name=ticks_executed,json=ticksExecuted,proto3" json:"ticks_executed,omitempty"`
	FramesExecuted uint32                 `protobuf:"varint,2,opt,name=frames_executed,json=framesExecuted,proto3" json:"frames_executed,omitempty"`
	Metrics        *MetricsSnapshot       `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StepFramesResponse) Reset() {
	*x = StepFramesResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepFramesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepFramesResponse) ProtoMessage() {}

func (x *StepFramesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepFramesResponse.ProtoReflect.Descriptor instead.
func (*StepFramesResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{30}
}

func (x *StepFramesResponse) GetTicksExecuted() uint32 {
	if x != nil {
		return x.TicksExecuted
	}
	return 0
}

func (x *StepFramesResponse) GetFramesExecuted() uint32 {
	if x != nil {
		return x.FramesExecuted
	}
	return 0
}

func (x *StepFramesResponse) GetMetrics() *MetricsSnapshot {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type WaitUntilReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Criteria      *WaitCriteria          `protobuf:"bytes,1,opt,name=criteria,proto3" json:"criteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitUntilReadyRequest) Reset() {
	*x = WaitUntilReadyRequest{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitUntilReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitUntilReadyRequest) ProtoMessage() {}

func (x *WaitUntilReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitUntilReadyRequest.ProtoReflect.Descriptor instead.
func (*WaitUntilReadyRequest) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{31}
}

func (x *WaitUntilReadyRequest) GetCriteria() *WaitCriteria {
	if x != nil {
		return x.Criteria
	}
	return nil
}

type WaitUntilReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readiness     *Readiness             `protobuf:"bytes,1,opt,name=readiness,proto3" json:"readiness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitUntilReadyResponse) Reset() {
	*x = WaitUntilReadyResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitUntilReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitUntilReadyResponse) ProtoMessage() {}

func (x *WaitUntilReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitUntilReadyResponse.ProtoReflect.Descriptor instead.
func (*WaitUntilReadyResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{32}
}

func (x *WaitUntilReadyResponse) GetReadiness() *Readiness {
	if x != nil {
		return x.Readiness
	}
	return nil
}

type ResetMetricsWindowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *MetricsSnapshot       `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetMetricsWindowResponse) Reset() {
	*x = ResetMetricsWindowResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetMetricsWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetMetricsWindowResponse) ProtoMessage() {}

func (x *ResetMetricsWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetMetricsWindowResponse.ProtoReflect.Descriptor instead.
func (*ResetMetricsWindowResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{33}
}

func (x *ResetMetricsWindowResponse) GetMetrics() *MetricsSnapshot {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readiness     *Readiness             `protobuf:"bytes,1,opt,name=readiness,proto3" json:"readiness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{34}
}

func (x *StopResponse) GetReadiness() *Readiness {
	if x != nil {
		return x.Readiness
	}
	return nil
}

type CaptureScreenshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactName  string                 `protobuf:"bytes,1,opt,name=artifact_name,json=artifactName,proto3" json:"artifact_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureScreenshotRequest) Reset() {
	*x = CaptureScreenshotRequest{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureScreenshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureScreenshotRequest) ProtoMessage() {}

func (x *CaptureScreenshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureScreenshotRequest.ProtoReflect.Descriptor instead.
func (*CaptureScreenshotRequest) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{35}
}

func (x *CaptureScreenshotRequest) GetArtifactName() string {
	if x != nil {
		return x.ArtifactName
	}
	return ""
}

type CaptureScreenshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureScreenshotResponse) Reset() {
	*x = CaptureScreenshotResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureScreenshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureScreenshotResponse) ProtoMessage() {}

func (x *CaptureScreenshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureScreenshotResponse.ProtoReflect.Descriptor instead.
func (*CaptureScreenshotResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{36}
}

func (x *CaptureScreenshotResponse) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type ExportTraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactName  string                 `protobuf:"bytes,1,opt,name=artifact_name,json=artifactName,proto3" json:"artifact_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTraceRequest) Reset() {
	*x = ExportTraceRequest{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTraceRequest) ProtoMessage() {}

func (x *ExportTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTraceRequest.ProtoReflect.Descriptor instead.
func (*ExportTraceRequest) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{37}
}

func (x *ExportTraceRequest) GetArtifactName() string {
	if x != nil {
		return x.ArtifactName
	}
	return ""
}

type ExportTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *Artifact              `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTraceResponse) Reset() {
	*x = ExportTraceResponse{}
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTraceResponse) ProtoMessage() {}

func (x *ExportTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogoxel_automation_v1_automation_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTraceResponse.ProtoReflect.Descriptor instead.
func (*ExportTraceResponse) Descriptor() ([]byte, []int) {
	return file_gogoxel_automation_v1_automation_proto_rawDescGZIP(), []int{38}
}

func (x *ExportTraceResponse) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

var File_gogoxel_automation_v1_automation_proto protoreflect.FileDescriptor

const file_gogoxel_automation_v1_automation_proto_rawDesc = "" +
	"\n" +
	"&gogoxel/automation/v1/automation.proto\x12\x15gogoxel.automation.v1\"\a\n" +
	"\x05Empty\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"\x93\x01\n" +
	"\x06Camera\x12:\n" +
	"\bposition\x18\x01 \x01(\v2\x1e.gogoxel.automation.v1.Vector3R\bposition\x12\x17\n" +
	"\ayaw_deg\x18\x02 \x01(\x02R\x06yawDeg\x12\x1b\n" +
	"\tpitch_deg\x18\x03 \x01(\x02R\bpitchDeg\x12\x17\n" +
	"\afov_deg\x18\x04 \x01(\x02R\x06fovDeg\"\xea\x01\n" +
	"\tReadiness\x12-\n" +
	"\x12engine_initialized\x18\x01 \x01(\bR\x11engineInitialized\x121\n" +
	"\x14renderer_initialized\x18\x02 \x01(\bR\x13rendererInitialized\x12!\n" +
	"\fscene_loaded\x18\x03 \x01(\bR\vsceneLoaded\x12+\n" +
	"\x11streaming_planned\x18\x04 \x01(\bR\x10streamingPlanned\x12+\n" +
	"\x11streaming_settled\x18\x05 \x01(\bR\x10streamingSettled\"\xc4\x01\n" +
	"\fWaitCriteria\x12)\n" +
	"\x10require_renderer\x18\x01 \x01(\bR\x0frequireRenderer\x120\n" +
	"\x14require_scene_loaded\x18\x02 \x01(\bR\x12requireSceneLoaded\x12:\n" +
	"\x19require_streaming_settled\x18\x03 \x01(\bR\x17requireStreamingSettled\x12\x1b\n" +
	"\tmax_ticks\x18\x04 \x01(\rR\bmaxTicks\"\xd4\b\n" +
	"\x0fMetricsSnapshot\x125\n" +
	"\x06camera\x18\x01 \x01(\v2\x1d.gogoxel.automation.v1.CameraR\x06camera\x12+\n" +
	"\x11current_generator\x18\x02 \x01(\tR\x10currentGenerator\x12\x1b\n" +
	"\tram_bytes\x18\x03 \x01(\x04R\bramBytes\x12(\n" +
	"\x10system_ram_bytes\x18\x04 \x01(\x04R\x0esystemRamBytes\x12\x1d\n" +
	"\n" +
	"vram_bytes\x18\x05 \x01(\x04R\tvramBytes\x12&\n" +
	"\x0fchunk_ram_bytes\x18\x06 \x01(\x04R\rchunkRamBytes\x12\x1d\n" +
	"\n" +
	"node_count\x18\a \x01(\x04R\tnodeCount\x12\x1f\n" +
	"\vbrick_count\x18\b \x01(\x04R\n" +
	"brickCount\x12\x1d\n" +
	"\n" +
	"world_size\x18\t \x01(\x04R\tworldSize\x120\n" +
	"\x14resident_brick_count\x18\n" +
	" \x01(\x04R\x12residentBrickCount\x126\n" +
	"\x17streaming_desired_ready\x18\v \x01(\bR\x15streamingDesiredReady\x12E\n" +
	"\x1fstreaming_pending_desired_count\x18\f \x01(\x04R\x1cstreamingPendingDesiredCount\x128\n" +
	"\x18streaming_resident_limit\x18\r \x01(\x04R\x16streamingResidentLimit\x126\n" +
	"\x17streaming_upload_budget\x18\x0e \x01(\x04R\x15streamingUploadBudget\x12!\n" +
	"\fpresent_mode\x18\x0f \x01(\tR\vpresentMode\x12'\n" +
	"\x0frenderer_device\x18\x10 \x01(\tR\x0erendererDevice\x12\x1f\n" +
	"\vaverage_fps\x18\x11 \x01(\x01R\n" +
	"averageFps\x121\n" +
	"\x15average_frame_time_ms\x18\x12 \x01(\x01R\x12averageFrameTimeMs\x12)\n" +
	"\x11p95_frame_time_ms\x18\x13 \x01(\x01R\x0ep95FrameTimeMs\x12,\n" +
	"\x12frame_sample_count\x18\x14 \x01(\x04R\x10frameSampleCount\x128\n" +
	"\x19average_gpu_frame_time_ms\x18\x15 \x01(\x01R\x15averageGpuFrameTimeMs\x120\n" +
	"\x15p95_gpu_frame_time_ms\x18\x16 \x01(\x01R\x11p95GpuFrameTimeMs\x123\n" +
	"\x16gpu_frame_sample_count\x18\x17 \x01(\x04R\x13gpuFrameSampleCount\x123\n" +
	"\x16heap_alloc_delta_bytes\x18\x18 \x01(\x04R\x13heapAllocDeltaBytes\"q\n" +
	"\bArtifact\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12%\n" +
	"\x0erequested_name\x18\x02 \x01(\tR\rrequestedName\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"X\n" +
	"\x10NormalizedCursor\x12!\n" +
	"\fnormalized_x\x18\x01 \x01(\x02R\vnormalizedX\x12!\n" +
	"\fnormalized_y\x18\x02 \x01(\x02R\vnormalizedY\"<\n" +
	"\x10VoxelCoordinates\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\rR\x01z\"P\n" +
	"\x0eHealthResponse\x12>\n" +
	"\treadiness\x18\x01 \x01(\v2 .gogoxel.automation.v1.ReadinessR\treadiness\"J\n" +
	"\x11GetCameraResponse\x125\n" +
	"\x06camera\x18\x01 \x01(\v2\x1d.gogoxel.automation.v1.CameraR\x06camera\"V\n" +
	"\x12GetMetricsResponse\x12@\n" +
	"\ametrics\x18\x01 \x01(\v2&.gogoxel.automation.v1.MetricsSnapshotR\ametrics\"U\n" +
	"\x13ResetEngineResponse\x12>\n" +
	"\treadiness\x18\x01 \x01(\v2 .gogoxel.automation.v1.ReadinessR\treadiness\"}\n" +
	"\x14LoadGeneratorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\achunk_x\x18\x02 \x01(\x05R\x06chunkX\x12\x17\n" +
	"\achunk_y\x18\x03 \x01(\x05R\x06chunkY\x12\x1f\n" +
	"\vchunk_range\x18\x04 \x01(\rR\n" +
	"chunkRange\"W\n" +
	"\x15LoadGeneratorResponse\x12>\n" +
	"\treadiness\x18\x01 \x01(\v2 .gogoxel.automation.v1.ReadinessR\treadiness\"I\n" +
	"\x10SetCameraRequest\x125\n" +
	"\x06camera\x18\x01 \x01(\v2\x1d.gogoxel.automation.v1.CameraR\x06camera\"J\n" +
	"\x11SetCameraResponse\x125\n" +
	"\x06camera\x18\x01 \x01(\v2\x1d.gogoxel.automation.v1.CameraR\x06camera\"@\n" +
	"\x1cSetSimulationTickRateRequest\x12 \n" +
	"\ftick_rate_hz\x18\x01 \x01(\rR\n" +
	"tickRateHz\"A\n" +
	"\x1dSetSimulationTickRateResponse\x12 \n" +
	"\ftick_rate_hz\x18\x01 \x01(\rR\n" +
	"tickRateHz\"g\n" +
	"\x13InjectActionRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x128\n" +
	"\x05state\x18\x02 \x01(\x0e2\".gogoxel.automation.v1.ActionStateR\x05state\"V\n" +
	"\x14InjectActionResponse\x12>\n" +
	"\treadiness\x18\x01 \x01(\v2 .gogoxel.automation.v1.ReadinessR\treadiness\"A\n" +
	"\x1aSetSelectedMaterialRequest\x12#\n" +
	"\rmaterial_name\x18\x01 \x01(\tR\fmaterialName\"B\n" +
	"\x1bSetSelectedMaterialResponse\x12#\n" +
	"\rmaterial_name\x18\x01 \x01(\tR\fmaterialName\"\x8b\x01\n" +
	"\x13EditAtCursorRequest\x12?\n" +
	"\x06cursor\x18\x01 \x01(\v2'.gogoxel.automation.v1.NormalizedCursorR\x06cursor\x123\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1f.gogoxel.automation.v1.EditModeR\x04mode\"\xe7\x01\n" +
	"\x14EditAtCursorResponse\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\x12D\n" +
	"\thit_voxel\x18\x02 \x01(\v2'.gogoxel.automation.v1.VoxelCoordinatesR\bhitVoxel\x12J\n" +
	"\ftarget_voxel\x18\x03 \x01(\v2'.gogoxel.automation.v1.VoxelCoordinatesR\vtargetVoxel\x12#\n" +
	"\rmaterial_name\x18\x04 \x01(\tR\fmaterialName\"6\n" +
	"\x15ClickUiElementRequest\x12\x1d\n" +
	"\n" +
	"logical_id\x18\x01 \x01(\tR\tlogicalId\"X\n" +
	"\x16ClickUiElementResponse\x12>\n" +
	"\treadiness\x18\x01 \x01(\v2 .gogoxel.automation.v1.ReadinessR\treadiness\"(\n" +
	"\x10StepTicksRequest\x12\x14\n" +
	"\x05ticks\x18\x01 \x01(\rR\x05ticks\"\xa5\x01\n" +
	"\x11StepTicksResponse\x12%\n" +
	"\x0eticks_executed\x18\x01 \x01(\rR\rticksExecuted\x12'\n" +
	"\x0fframes_executed\x18\x02 \x01(\rR\x0eframesExecuted\x12@\n" +
	"\ametrics\x18\x03 \x01(\v2&.gogoxel.automation.v1.MetricsSnapshotR\ametrics\"+\n" +
	"\x11StepFramesRequest\x12\x16\n" +
	"\x06frames\x18\x01 \x01(\rR\x06frames\"\xa6\x01\n" +
	"\x12StepFramesResponse\x12%\n" +
	"\x0eticks_executed\x18\x01 \x01(\rR\rticksExecuted\x12'\n" +
	"\x0fframes_executed\x18\x02 \x01(\rR\x0eframesExecuted\x12@\n" +
	"\ametrics\x18\x03 \x01(\v2&.gogoxel.automation.v1.MetricsSnapshotR\ametrics\"X\n" +
	"\x15WaitUntilReadyRequest\x12?\n" +
	"\bcriteria\x18\x01 \x01(\v2#.gogoxel.automation.v1.WaitCriteriaR\bcriteria\"X\n" +
	"\x16WaitUntilReadyResponse\x12>\n" +
	"\treadiness\x18\x01 \x01(\v2 .gogoxel.automation.v1.ReadinessR\treadiness\"^\n" +
	"\x1aResetMetricsWindowResponse\x12@\n" +
	"\ametrics\x18\x01 \x01(\v2&.gogoxel.automation.v1.MetricsSnapshotR\ametrics\"N\n" +
	"\fStopResponse\x12>\n" +
	"\treadiness\x18\x01 \x01(\v2 .gogoxel.automation.v1.ReadinessR\treadiness\"?\n" +
	"\x18CaptureScreenshotRequest\x12#\n" +
	"\rartifact_name\x18\x01 \x01(\tR\fartifactName\"X\n" +
	"\x19CaptureScreenshotResponse\x12;\n" +
	"\bartifact\x18\x01 \x01(\v2\x1f.gogoxel.automation.v1.ArtifactR\bartifact\"9\n" +
	"\x12ExportTraceRequest\x12#\n" +
	"\rartifact_name\x18\x01 \x01(\tR\fartifactName\"R\n" +
	"\x13ExportTraceResponse\x12;\n" +
	"\bartifact\x18\x01 \x01(\v2\x1f.gogoxel.automation.v1.ArtifactR\bartifact*]\n" +
	"\vActionState\x12\x1c\n" +
	"\x18ACTION_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ACTION_STATE_PRESS\x10\x01\x12\x18\n" +
	"\x14ACTION_STATE_RELEASE\x10\x02*P\n" +
	"\bEditMode\x12\x19\n" +
	"\x15EDIT_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fEDIT_MODE_PLACE\x10\x01\x12\x14\n" +
	"\x10EDIT_MODE_REMOVE\x10\x022\x92\x02\n" +
	"\x15AutomationReadService\x12M\n" +
	"\x06Health\x12\x1c.gogoxel.automation.v1.Empty\x1a%.gogoxel.automation.v1.HealthResponse\x12S\n" +
	"\tGetCamera\x12\x1c.gogoxel.automation.v1.Empty\x1a(.gogoxel.automation.v1.GetCameraResponse\x12U\n" +
	"\n" +
	"GetMetrics\x12\x1c.gogoxel.automation.v1.Empty\x1a).gogoxel.automation.v1.GetMetricsResponse2\xe7\n" +
	"\n" +
	"\x18AutomationControlService\x12W\n" +
	"\vResetEngine\x12\x1c.gogoxel.automation.v1.Empty\x1a*.gogoxel.automation.v1.ResetEngineResponse\x12j\n" +
	"\rLoadGenerator\x12+.gogoxel.automation.v1.LoadGeneratorRequest\x1a,.gogoxel.automation.v1.LoadGeneratorResponse\x12^\n" +
	"\tSetCamera\x12'.gogoxel.automation.v1.SetCameraRequest\x1a(.gogoxel.automation.v1.SetCameraResponse\x12\x82\x01\n" +
	"\x15SetSimulationTickRate\x123.gogoxel.automation.v1.SetSimulationTickRateRequest\x1a4.gogoxel.automation.v1.SetSimulationTickRateResponse\x12g\n" +
	"\fInjectAction\x12*.gogoxel.automation.v1.InjectActionRequest\x1a+.gogoxel.automation.v1.InjectActionResponse\x12|\n" +
	"\x13SetSelectedMaterial\x121.gogoxel.automation.v1.SetSelectedMaterialRequest\x1a2.gogoxel.automation.v1.SetSelectedMaterialResponse\x12g\n" +
	"\fEditAtCursor\x12*.gogoxel.automation.v1.EditAtCursorRequest\x1a+.gogoxel.automation.v1.EditAtCursorResponse\x12m\n" +
	"\x0eClickUiElement\x12,.gogoxel.automation.v1.ClickUiElementRequest\x1a-.gogoxel.automation.v1.ClickUiElementResponse\x12^\n" +
	"\tStepTicks\x12'.gogoxel.automation.v1.StepTicksRequest\x1a(.gogoxel.automation.v1.StepTicksResponse\x12a\n" +
	"\n" +
	"StepFrames\x12(.gogoxel.automation.v1.StepFramesRequest\x1a).gogoxel.automation.v1.StepFramesResponse\x12m\n" +
	"\x0eWaitUntilReady\x12,.gogoxel.automation.v1.WaitUntilReadyRequest\x1a-.gogoxel.automation.v1.WaitUntilReadyResponse\x12e\n" +
	"\x12ResetMetricsWindow\x12\x1c.gogoxel.automation.v1.Empty\x1a1.gogoxel.automation.v1.ResetMetricsWindowResponse\x12I\n" +
	"\x04Stop\x12\x1c.gogoxel.automation.v1.Empty\x1a#.gogoxel.automation.v1.StopResponse2\xf9\x01\n" +
	"\x19AutomationArtifactService\x12v\n" +
	"\x11CaptureScreenshot\x12/.gogoxel.automation.v1.CaptureScreenshotRequest\x1a0.gogoxel.automation.v1.CaptureScreenshotResponse\x12d\n" +
	"\vExportTrace\x12).gogoxel.automation.v1.ExportTraceRequest\x1a*.gogoxel.automation.v1.ExportTraceResponseB-Z+Gogoxel/internal/automation/pb;automationpbb\x06proto3"

var (
	file_gogoxel_automation_v1_automation_proto_rawDescOnce sync.Once
	file_gogoxel_automation_v1_automation_proto_rawDescData []byte
)

func file_gogoxel_automation_v1_automation_proto_rawDescGZIP() []byte {
	file_gogoxel_automation_v1_automation_proto_rawDescOnce.Do(func() {
		file_gogoxel_automation_v1_automation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gogoxel_automation_v1_automation_proto_rawDesc), len(file_gogoxel_automation_v1_automation_proto_rawDesc)))
	})
	return file_gogoxel_automation_v1_automation_proto_rawDescData
}

var file_gogoxel_automation_v1_automation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gogoxel_automation_v1_automation_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_gogoxel_automation_v1_automation_proto_goTypes = []any{
	(ActionState)(0),                      // 0: gogoxel.automation.v1.ActionState
	(EditMode)(0),                         // 1: gogoxel.automation.v1.EditMode
	(*Empty)(nil),                         // 2: gogoxel.automation.v1.Empty
	(*Vector3)(nil),                       // 3: gogoxel.automation.v1.Vector3
	(*Camera)(nil),                        // 4: gogoxel.automation.v1.Camera
	(*Readiness)(nil),                     // 5: gogoxel.automation.v1.Readiness
	(*WaitCriteria)(nil),                  // 6: gogoxel.automation.v1.WaitCriteria
	(*MetricsSnapshot)(nil),               // 7: gogoxel.automation.v1.MetricsSnapshot
	(*Artifact)(nil),                      // 8: gogoxel.automation.v1.Artifact
	(*NormalizedCursor)(nil),              // 9: gogoxel.automation.v1.NormalizedCursor
	(*VoxelCoordinates)(nil),              // 10: gogoxel.automation.v1.VoxelCoordinates
	(*HealthResponse)(nil),                // 11: gogoxel.automation.v1.HealthResponse
	(*GetCameraResponse)(nil),             // 12: gogoxel.automation.v1.GetCameraResponse
	(*GetMetricsResponse)(nil),            // 13: gogoxel.automation.v1.GetMetricsResponse
	(*ResetEngineResponse)(nil),           // 14: gogoxel.automation.v1.ResetEngineResponse
	(*LoadGeneratorRequest)(nil),          // 15: gogoxel.automation.v1.LoadGeneratorRequest
	(*LoadGeneratorResponse)(nil),         // 16: gogoxel.automation.v1.LoadGeneratorResponse
	(*SetCameraRequest)(nil),              // 17: gogoxel.automation.v1.SetCameraRequest
	(*SetCameraResponse)(nil),             // 18: gogoxel.automation.v1.SetCameraResponse
	(*SetSimulationTickRateRequest)(nil),  // 19: gogoxel.automation.v1.SetSimulationTickRateRequest
	(*SetSimulationTickRateResponse)(nil), // 20: gogoxel.automation.v1.SetSimulationTickRateResponse
	(*InjectActionRequest)(nil),           // 21: gogoxel.automation.v1.InjectActionRequest
	(*InjectActionResponse)(nil),          // 22: gogoxel.automation.v1.InjectActionResponse
	(*SetSelectedMaterialRequest)(nil),    // 23: gogoxel.automation.v1.SetSelectedMaterialRequest
	(*SetSelectedMaterialResponse)(nil),   // 24: gogoxel.automation.v1.SetSelectedMaterialResponse
	(*EditAtCursorRequest)(nil),           // 25: gogoxel.automation.v1.EditAtCursorRequest
	(*EditAtCursorResponse)(nil),          // 26: gogoxel.automation.v1.EditAtCursorResponse
	(*ClickUiElementRequest)(nil),         // 27: gogoxel.automation.v1.ClickUiElementRequest
	(*ClickUiElementResponse)(nil),        // 28: gogoxel.automation.v1.ClickUiElementResponse
	(*StepTicksRequest)(nil),              // 29: gogoxel.automation.v1.StepTicksRequest
	(*StepTicksResponse)(nil),             // 30: gogoxel.automation.v1.StepTicksResponse
	(*StepFramesRequest)(nil),             // 31: gogoxel.automation.v1.StepFramesRequest
	(*StepFramesResponse)(nil),            // 32: gogoxel.automation.v1.StepFramesResponse
	(*WaitUntilReadyRequest)(nil),         // 33: gogoxel.automation.v1.WaitUntilReadyRequest
	(*WaitUntilReadyResponse)(nil),        // 34: gogoxel.automation.v1.WaitUntilReadyResponse
	(*ResetMetricsWindowResponse)(nil),    // 35: gogoxel.automation.v1.ResetMetricsWindowResponse
	(*StopResponse)(nil),                  // 36: gogoxel.automation.v1.StopResponse
	(*CaptureScreenshotRequest)(nil),      // 37: gogoxel.automation.v1.CaptureScreenshotRequest
	(*CaptureScreenshotResponse)(nil),     // 38: gogoxel.automation.v1.CaptureScreenshotResponse
	(*ExportTraceRequest)(nil),            // 39: gogoxel.automation.v1.ExportTraceRequest
	(*ExportTraceResponse)(nil),           // 40: gogoxel.automation.v1.ExportTraceResponse
}
var file_gogoxel_automation_v1_automation_proto_depIdxs = []int32{
	3,  // 0: gogoxel.automation.v1.Camera.position:type_name -> gogoxel.automation.v1.Vector3
	4,  // 1: gogoxel.automation.v1.MetricsSnapshot.camera:type_name -> gogoxel.automation.v1.Camera
	5,  // 2: gogoxel.automation.v1.HealthResponse.readiness:type_name -> gogoxel.automation.v1.Readiness
	4,  // 3: gogoxel.automation.v1.GetCameraResponse.camera:type_name -> gogoxel.automation.v1.Camera
	7,  // 4: gogoxel.automation.v1.GetMetricsResponse.metrics:type_name -> gogoxel.automation.v1.MetricsSnapshot
	5,  // 5: gogoxel.automation.v1.ResetEngineResponse.readiness:type_name -> gogoxel.automation.v1.Readiness
	5,  // 6: gogoxel.automation.v1.LoadGeneratorResponse.readiness:type_name -> gogoxel.automation.v1.Readiness
	4,  // 7: gogoxel.automation.v1.SetCameraRequest.camera:type_name -> gogoxel.automation.v1.Camera
	4,  // 8: gogoxel.automation.v1.SetCameraResponse.camera:type_name -> gogoxel.automation.v1.Camera
	0,  // 9: gogoxel.automation.v1.InjectActionRequest.state:type_name -> gogoxel.automation.v1.ActionState
	5,  // 10: gogoxel.automation.v1.InjectActionResponse.readiness:type_name -> gogoxel.automation.v1.Readiness
	9,  // 11: gogoxel.automation.v1.EditAtCursorRequest.cursor:type_name -> gogoxel.automation.v1.NormalizedCursor
	1,  // 12: gogoxel.automation.v1.EditAtCursorRequest.mode:type_name -> gogoxel.automation.v1.EditMode
	10, // 13: gogoxel.automation.v1.EditAtCursorResponse.hit_voxel:type_name -> gogoxel.automation.v1.VoxelCoordinates
	10, // 14: gogoxel.automation.v1.EditAtCursorResponse.target_voxel:type_name -> gogoxel.automation.v1.VoxelCoordinates
	5,  // 15: gogoxel.automation.v1.ClickUiElementResponse.readiness:type_name -> gogoxel.automation.v1.Readiness
	7,  // 16: gogoxel.automation.v1.StepTicksResponse.metrics:type_name -> gogoxel.automation.v1.MetricsSnapshot
	7,  // 17: gogoxel.automation.v1.StepFramesResponse.metrics:type_name -> gogoxel.automation.v1.MetricsSnapshot
	6,  // 18: gogoxel.automation.v1.WaitUntilReadyRequest.criteria:type_name -> gogoxel.automation.v1.WaitCriteria
	5,  // 19: gogoxel.automation.v1.WaitUntilReadyResponse.readiness:type_name -> gogoxel.automation.v1.Readiness
	7,  // 20: gogoxel.automation.v1.ResetMetricsWindowResponse.metrics:type_name -> gogoxel.automation.v1.MetricsSnapshot
	5,  // 21: gogoxel.automation.v1.StopResponse.readiness:type_name -> gogoxel.automation.v1.Readiness
	8,  // 22: gogoxel.automation.v1.CaptureScreenshotResponse.artifact:type_name -> gogoxel.automation.v1.Artifact
	8,  // 23: gogoxel.automation.v1.ExportTraceResponse.artifact:type_name -> gogoxel.automation.v1.Artifact
	2,  // 24: gogoxel.automation.v1.AutomationReadService.Health:input_type -> gogoxel.automation.v1.Empty
	2,  // 25: gogoxel.automation.v1.AutomationReadService.GetCamera:input_type -> gogoxel.automation.v1.Empty
	2,  // 26: gogoxel.automation.v1.AutomationReadService.GetMetrics:input_type -> gogoxel.automation.v1.Empty
	2,  // 27: gogoxel.automation.v1.AutomationControlService.ResetEngine:input_type -> gogoxel.automation.v1.Empty
	15, // 28: gogoxel.automation.v1.AutomationControlService.LoadGenerator:input_type -> gogoxel.automation.v1.LoadGeneratorRequest
	17, // 29: gogoxel.automation.v1.AutomationControlService.SetCamera:input_type -> gogoxel.automation.v1.SetCameraRequest
	19, // 30: gogoxel.automation.v1.AutomationControlService.SetSimulationTickRate:input_type -> gogoxel.automation.v1.SetSimulationTickRateRequest
	21, // 31: gogoxel.automation.v1.AutomationControlService.InjectAction:input_type -> gogoxel.automation.v1.InjectActionRequest
	23, // 32: gogoxel.automation.v1.AutomationControlService.SetSelectedMaterial:input_type -> gogoxel.automation.v1.SetSelectedMaterialRequest
	25, // 33: gogoxel.automation.v1.AutomationControlService.EditAtCursor:input_type -> gogoxel.automation.v1.EditAtCursorRequest
	27, // 34: gogoxel.automation.v1.AutomationControlService.ClickUiElement:input_type -> gogoxel.automation.v1.ClickUiElementRequest
	29, // 35: gogoxel.automation.v1.AutomationControlService.StepTicks:input_type -> gogoxel.automation.v1.StepTicksRequest
	31, // 36: gogoxel.automation.v1.AutomationControlService.StepFrames:input_type -> gogoxel.automation.v1.StepFramesRequest
	33, // 37: gogoxel.automation.v1.AutomationControlService.WaitUntilReady:input_type -> gogoxel.automation.v1.WaitUntilReadyRequest
	2,  // 38: gogoxel.automation.v1.AutomationControlService.ResetMetricsWindow:input_type -> gogoxel.automation.v1.Empty
	2,  // 39: gogoxel.automation.v1.AutomationControlService.Stop:input_type -> gogoxel.automation.v1.Empty
	37, // 40: gogoxel.automation.v1.AutomationArtifactService.CaptureScreenshot:input_type -> gogoxel.automation.v1.CaptureScreenshotRequest
	39, // 41: gogoxel.automation.v1.AutomationArtifactService.ExportTrace:input_type -> gogoxel.automation.v1.ExportTraceRequest
	11, // 42: gogoxel.automation.v1.AutomationReadService.Health:output_type -> gogoxel.automation.v1.HealthResponse
	12, // 43: gogoxel.automation.v1.AutomationReadService.GetCamera:output_type -> gogoxel.automation.v1.GetCameraResponse
	13, // 44: gogoxel.automation.v1.AutomationReadService.GetMetrics:output_type -> gogoxel.automation.v1.GetMetricsResponse
	14, // 45: gogoxel.automation.v1.AutomationControlService.ResetEngine:output_type -> gogoxel.automation.v1.ResetEngineResponse
	16, // 46: gogoxel.automation.v1.AutomationControlService.LoadGenerator:output_type -> gogoxel.automation.v1.LoadGeneratorResponse
	18, // 47: gogoxel.automation.v1.AutomationControlService.SetCamera:output_type -> gogoxel.automation.v1.SetCameraResponse
	20, // 48: gogoxel.automation.v1.AutomationControlService.SetSimulationTickRate:output_type -> gogoxel.automation.v1.SetSimulationTickRateResponse
	22, // 49: gogoxel.automation.v1.AutomationControlService.InjectAction:output_type -> gogoxel.automation.v1.InjectActionResponse
	24, // 50: gogoxel.automation.v1.AutomationControlService.SetSelectedMaterial:output_type -> gogoxel.automation.v1.SetSelectedMaterialResponse
	26, // 51: gogoxel.automation.v1.AutomationControlService.EditAtCursor:output_type -> gogoxel.automation.v1.EditAtCursorResponse
	28, // 52: gogoxel.automation.v1.AutomationControlService.ClickUiElement:output_type -> gogoxel.automation.v1.ClickUiElementResponse
	30, // 53: gogoxel.automation.v1.AutomationControlService.StepTicks:output_type -> gogoxel.automation.v1.StepTicksResponse
	32, // 54: gogoxel.automation.v1.AutomationControlService.StepFrames:output_type -> gogoxel.automation.v1.StepFramesResponse
	34, // 55: gogoxel.automation.v1.AutomationControlService.WaitUntilReady:output_type -> gogoxel.automation.v1.WaitUntilReadyResponse
	35, // 56: gogoxel.automation.v1.AutomationControlService.ResetMetricsWindow:output_type -> gogoxel.automation.v1.ResetMetricsWindowResponse
	36, // 57: gogoxel.automation.v1.AutomationControlService.Stop:output_type -> gogoxel.automation.v1.StopResponse
	38, // 58: gogoxel.automation.v1.AutomationArtifactService.CaptureScreenshot:output_type -> gogoxel.automation.v1.CaptureScreenshotResponse
	40, // 59: gogoxel.automation.v1.AutomationArtifactService.ExportTrace:output_type -> gogoxel.automation.v1.ExportTraceResponse
	42, // [42:60] is the sub-list for method output_type
	24, // [24:42] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_gogoxel_automation_v1_automation_proto_init() }
func file_gogoxel_automation_v1_automation_proto_init() {
	if File_gogoxel_automation_v1_automation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gogoxel_automation_v1_automation_proto_rawDesc), len(file_gogoxel_automation_v1_automation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_gogoxel_automation_v1_automation_proto_goTypes,
		DependencyIndexes: file_gogoxel_automation_v1_automation_proto_depIdxs,
		EnumInfos:         file_gogoxel_automation_v1_automation_proto_enumTypes,
		MessageInfos:      file_gogoxel_automation_v1_automation_proto_msgTypes,
	}.Build()
	File_gogoxel_automation_v1_automation_proto = out.File
	file_gogoxel_automation_v1_automation_proto_goTypes = nil
	file_gogoxel_automation_v1_automation_proto_depIdxs = nil
}
