#version 450

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

layout(std430, binding = 0) readonly buffer InputData {
    uint data[];
} src;

layout(r8ui, binding = 1) writeonly uniform uimage3D targetImage;

void main() {
    ivec3 texelCoord = ivec3(gl_GlobalInvocationID.xyz);
    ivec3 size = imageSize(targetImage);

    if (texelCoord.x >= size.x || texelCoord.y >= size.y || texelCoord.z >= size.z) {
        return;
    }

    uint totalVoxelIndex = texelCoord.z * (size.x * size.y) + texelCoord.y * size.x + texelCoord.x;

    uint packedVoxelCount = (uint(size.x) * uint(size.y) * uint(size.z) + 3u) / 4u;
    uint arrayIndex = totalVoxelIndex / 4u;
    uint byteOffset = totalVoxelIndex % 4u;
    uint packedFourVoxels = src.data[arrayIndex];
    uint voxelID = (packedFourVoxels >> (byteOffset * 8)) & 0xFFu;
    imageStore(targetImage, texelCoord, uvec4(voxelID, 0u, 0u, 0u));
}
